App.canned_images = [
  { name:       "Challenge Accepted",
    filename:   "challenge-accepted.png",
    medium:     "medium_challenge-accepted.png",
    thumbnail:  "thumbnail_challenge-accepted.jpg",
    width:      786,
    height:     953 },
  { name:       "Derpina",
    filename:   "derpina.png",
    medium:     "medium_derpina.png",
    thumbnail:  "thumbnail_derpina.jpg",
    width:      1000,
    height:     951 },
  { name:       "Facepalm Picard",
    filename:   "facepalm-picard.png",
    medium:     "medium_facepalm-picard.png",
    thumbnail:  "thumbnail_facepalm-picard.jpg",
    width:      1500,
    height:     912 },
  # { name:       "First-world Problems",
  #   filename:   "first-world-problems.jpg",
  #   medium:     "medium_first-world-problems.jpg",
  #   thumbnail:  "thumbnail_first-world-problems.jpg",
  #   width:      839,
  #   height:     560 },
  { name:       "Freddie Mercury",
    filename:   "freddie-mercury.png",
    medium:     "medium_freddie-mercury.png",
    thumbnail:  "thumbnail_freddie-mercury.jpg",
    width:      1052,
    height:     2134 },
  # { name:       "Futurama Fry",
  #   filename:   "futurama-fry.jpg",
  #   medium:     "medium_futurama-fry.jpg",
  #   thumbnail:  "thumbnail_futurama-fry.jpg",
  #   width:      1030,
  #   height:     773 },
  { name:       "Happy Overload",
    filename:   "happy-overload.png",
    medium:     "medium_happy-overload.png",
    thumbnail:  "thumbnail_happy-overload.jpg",
    width:      1250,
    height:     1181 },
  { name:       "I Don't Always ...",
    filename:   "i-dont-always.jpg",
    medium:     "medium_i-dont-always.jpg",
    thumbnail:  "thumbnail_i-dont-always.jpg",
    width:      837,
    height:     1051 },
  { name:       "Jacky Chan",
    filename:   "jacky-chan.png",
    medium:     "medium_jacky-chan.png",
    thumbnail:  "thumbnail_jacky-chan.jpg",
    width:      1500,
    height:     951 },
  { name:       "Joseph Ducreux",
    filename:   "joseph_ducreux.jpg",
    medium:     "medium_joseph_ducreux.jpg",
    thumbnail:  "thumbnail_joseph_ducreux.jpg",
    width:      864,
    height:     1135 },
  { name:       "Keep Calm",
    filename:   "keep_calm.png",
    medium:     "medium_keep_calm.png",
    thumbnail:  "thumbnail_keep_calm.jpg",
    width:      1000,
    height:     1000 },
  # { name:       "Koala Can't Believe It",
  #   filename:   "koala-cant-believe-it.jpg",
  #   medium:     "medium_koala-cant-believe-it.jpg",
  #   thumbnail:  "thumbnail_koala-cant-believe-it.jpg",
  #   width:      777,
  #   height:     1032 },
  { name:       "Like a Sir",
    filename:   "like_a_sir.png",
    medium:     "medium_like_a_sir.png",
    thumbnail:  "thumbnail_like_a_sir.jpg",
    width:      1501,
    height:     1179 },
  { name:       "LOL Crazy",
    filename:   "lol-crazy.png",
    medium:     "medium_lol-crazy.png",
    thumbnail:  "thumbnail_lol-crazy.jpg",
    width:      928,
    height:     1125 },
  { name:       "One Does Not Simply ...",
    filename:   "one-does-not-simply.jpg",
    medium:     "medium_one-does-not-simply.jpg",
    thumbnail:  "thumbnail_one_does_not_simply.jpg",
    width:      916,
    height:     541 },
  { name:       "Pedobear",
    filename:   "pedobear.png",
    medium:     "medium_pedobear.png",
    thumbnail:  "thumbnail_pedobear.jpg",
    width:      925,
    height:     1500 },
  { name:       "Philippine Map",
    filename:   "philippines-map.png",
    medium:     "medium_philippines-map.png",
    thumbnail:  "thumbnail_philippines-map.jpg",
    width:      1900,
    height:     1900 },
  { name:       "Philippine Sun",
    filename:   "philippine-sun.png",
    medium:     "medium_philippine-sun.png",
    thumbnail:  "thumbnail_philippine-sun.jpg",
    width:      1900,
    height:     1900 },
  { name:       "Philosoraptor",
    filename:   "philosoraptor.jpg",
    medium:     "medium_philosoraptor.jpg",
    thumbnail:  "thumbnail_philosoraptor.jpg",
    width:      773,
    height:     773 },
  { name:       "Rage Face",
    filename:   "rage_face.png",
    medium:     "medium_rage_face.png",
    thumbnail:  "thumbnail_rage_face.jpg",
    width:      1161,
    height:     1224 },
  { name:       "Reservoir Fuuus",
    filename:   "reservoir_fuuus.png",
    medium:     "medium_reservoir_fuuus.png",
    thumbnail:  "thumbnail_reservoir_fuuus.jpg",
    width:      1200,
    height:     703 },
  # { name:       "Success Kid",
  #   filename:   "success_kid.jpg",
  #   medium:     "medium_success_kid.jpg",
  #   thumbnail:  "thumbnail_success_kid.jpg",
  #   width:      708,
  #   height:     708 },
  { name:       "Surprised OMG",
    filename:   "surprised-omg.png",
    medium:     "medium_surprised-omg.png",
    thumbnail:  "thumbnail_surprised-omg.jpg",
    width:      1500,
    height:     1146 },
  { name:       "Trollface",
    filename:   "trollface.png",
    medium:     "medium_trollface.png",
    thumbnail:  "thumbnail_trollface.jpg",
    width:      1000,
    height:     850 },
  { name:       "Wait ...",
    filename:   "wait.png",
    medium:     "medium_wait.png",
    thumbnail:  "thumbnail_wait.jpg",
    width:      1278,
    height:     1246 },
  { name:       "What If I Told You ...",
    filename:   "what-if-i-told-you.jpg",
    medium:     "medium_what-if-i-told-you.jpg",
    thumbnail:  "thumbnail_what-if-i-told-you.jpg",
    width:      708,
    height:     708 },
  { name:       "Y U NO",
    filename:   "y-u-no.png",
    medium:     "medium_y-u-no.png",
    thumbnail:  "thumbnail_y_u_no.jpg",
    width:      1500,
    height:     1126 },
  { name:       "Yao Ming",
    filename:   "yao-ming.png",
    medium:     "medium_yao-ming.png",
    thumbnail:  "thumbnail_yao-ming.jpg",
    width:      1295,
    height:     1500 }
]

App.canned_images.each do |ci|
  ci.filename  = "http://#{App.url}/assets/library/#{ci.filename}"
  ci.medium    = "http://#{App.url}/assets/library/#{ci.medium}"
  ci.thumbnail = "http://#{App.url}/assets/library/#{ci.thumbnail}"
end
