development:
  sessions:
    default:
      database: customagic-development
      hosts:
        - localhost:27017
  options:
    use_utc: true
    raise_not_found_error: false

test:
  sessions:
    default:
      database: customagic-test
      hosts:
        - localhost:27017
  options:
    use_utc: true
    allow_dynamic_fields : false
    raise_not_found_error: false

staging:
  sessions:
    default:
      hosts: 
        - localhost:27017
      database: customagic-staging
  options:
    use_utc : true
    allow_dynamic_fields : false
    raise_not_found_error: false

production:
  sessions:
    default:
      hosts: 
        - mongodb.customagic.ph:27017 # doesn't work yet
      database: customagic
  options:
    use_utc : true
    allow_dynamic_fields : false
    raise_not_found_error: false