development:
  sessions:
    default:
      database: customagic-development
      hosts:
        - localhost:27017
  options:
    use_utc: true
    raise_not_found_error: false

test:
  sessions:
    default:
      database: customagic-test
      hosts:
        - localhost:27017
  options:
    use_utc: true
    raise_not_found_error: false

staging:
  sessions:
    default:
      hosts: 
        - localhost:27017
      database: customagic-staging
  options:
    use_utc : true
    raise_not_found_error: false

production:
  sessions:
    default:
      hosts: 
        - mongodb://heroku:fde6573767034583506a1e4e403c794e@dharma.mongohq.com:10080/app19768989 
        #<%= ENV['MONGOHQ_URL'] %> # mongodb.customagic.ph:27017 # doesn't work yet
      database: customagic
  options:
    use_utc : true
    raise_not_found_error: false