defaults: &defaults
  host: localhost
  port: 6379

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  host: grideye.redistogo.com
  password: ed82059bd102255572cd71c5cc80f41b
  port: 9483