defaults: &defaults
  host: localhost
  port: 6379

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  host: redis://redistogo:ed82059bd102255572cd71c5cc80f41b@grideye.redistogo.com
  port: 9483