defaults: &defaults
  host: localhost
  port: 6379

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  host: pub-redis-19687.us-east-1-2.1.ec2.garantiadata.com
  password: kdUx4MqsHttMNdW9
  port: 19687